name: raoproject
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  dio: ^5.3.3
  cupertino_icons: ^1.0.2
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  json_serializable: ^4.1.3
  build_runner: ^2.0.4
flutter:

  uses-material-design: true
  assets:
   - assets/images/splashScreen.gif
   - assets/images/logo.webp
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
